### ISSUE TITLE
OpenCube Data Browser

### ISSUE THREAD

**Issue by ghost** [opencube-toolkit/issues#1]
Is there a way when the measurement values are integers to have these aligned right in the cells instead of left (see screenshot)?
![screen shot 2014-09-19 at 11 37 48](https://cloud.githubusercontent.com/assets/437781/4333469/b0227962-3fe0-11e4-9bc8-bc6ad5b47e0a.png)

**Comment by cygri** [comment]
Perhaps the datatype of the literal can be used to decide on the best alignment. There's a [list of all built-in RDF datatypes](http://www.w3.org/TR/rdf11-concepts/#xsd-datatypes), and all numeric types should perhaps be right-justified.

**Comment by ghost** [comment]
Solved in newest release.
