### ISSUE TITLE
Error:    FComponent id cannot contain / : measureprop/measure 

### ISSUE THREAD

**Issue by NovasTaylor** [opencube-toolkit/issues#6]
After uploading an RDF datacube I receive the following error when creating the widget:

“The page at localhost:8888 says:
                FComponent id cannot contain / : measureprop/measure  “

Example:  URI for the datacube:
http://www.example.org/dc/foo/dataset/dataset-foo

Specify the dataCubeURI in the widget as:

{{#widget: DataCubeBrowser| dataCubeURI= 
http://www.example.org/dc/foo/dataset/dataset-foo| 
asynch='true' }} 

...results in the above error.

Thank you for attending to this error. I am happy to test the fix when it becomes available.
- Tim
  NovasTaylor@gmail.com

**Comment by forus** [comment]
@zeginis @NovasTaylor 
I've got the same error for my local dataset:

> jvm 1    | java.lang.RuntimeException: FComponent id cannot contain / : measurepts/1340995
> jvm 1    |    at com.fluidops.ajax.components.FComponent.<init>(FComponent.java:127)
> jvm 1    |    at com.fluidops.ajax.components.FCheckBox.<init>(FCheckBox.java:75)
> jvm 1    |    at com.fluidops.ajax.components.FCheckBox.<init>(FCheckBox.java:64)
> jvm 1    |    at org.certh.opencube.cubebrowser.DataCubeBrowser$2.<init>(DataCubeBrowser.java:498)

BTW I did not find the source code for `com.fluidops.ajax.components.FComponent`. Do you have plan to publish it?

**Comment by zeginis** [comment]
Hello,
I have fixed this issue.
You can download the fix from the OpenCube toolkit site the version v0.3b (http://opencube-toolkit.eu/opencube-browser/) and integrate it at your exising instalation of the toolkit.
See the download section for instruction how to integrate the fix.

Regards,
Dimitris
