### ISSUE TITLE
OLAP browser error

### ISSUE THREAD

**Issue by ghost** [opencube-toolkit/issues#7]
jvm 2    | PREFIX qb: http://purl.org/linked-data/cube#PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#PREFIX skos: http://www.w3.org/2004/02/skos/core#PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#select distinct ?graph_uri where{ GRAPH ?graph_uri{ {http://id.vlaanderen.be/statistieken/dq/kubus-studieniveau-nwwz#id rdf:type qb:DataSet }UNION {http://id.vlaanderen.be/statistieken/dq/kubus-studieniveau-nwwz#id rdf:type qb:Slice}}}
jvm 2    | org.openrdf.query.MalformedQueryException: Encountered " "/" "/ "" at line 30, column 265.
jvm 2    | Was expecting one of:
jvm 2    |     "(" ...
jvm 2    |     "!" ...
jvm 2    |     "^" ...
jvm 2    |     "a" ...
jvm 2    |     <Q_IRI_REF> ...
jvm 2    |     <PNAME_NS> ...
jvm 2    |     <PNAME_LN> ...
jvm 2    |     <VAR1> ...
jvm 2    |     <VAR2> ...
jvm 2    |  
jvm 2    |  at org.openrdf.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:198)
jvm 2    |  at org.openrdf.query.parser.QueryParserUtil.parseQuery(QueryParserUtil.java:133)
jvm 2    |  at org.openrdf.query.parser.QueryParserUtil.parseTupleQuery(QueryParserUtil.java:154)
jvm 2    |  at org.openrdf.repository.sail.SailRepositoryConnection.prepareTupleQuery(SailRepositoryConnection.java:171)
jvm 2    |  at org.openrdf.repository.sail.SailRepositoryConnection.prepareTupleQuery(SailRepositoryConnection.java:55)
jvm 2    |  at org.openrdf.repository.base.RepositoryConnectionWrapper.prepareTupleQuery(RepositoryConnectionWrapper.java:392)
jvm 2    |  at org.openrdf.repository.base.RepositoryConnectionBase.prepareTupleQuery(RepositoryConnectionBase.java:124)
jvm 2    |  at com.fluidops.iwb.monitoring.ReadMonitorRepositoryConnection.prepareTupleQuery(ReadMonitorRepositoryConnection.java:106)
jvm 2    |  at com.fluidops.iwb.api.query.FromStringQueryBuilder$FromStringTupleQueryBuilder$1.run(FromStringQueryBuilder.java:263)
jvm 2    |  at com.fluidops.iwb.api.query.FromStringQueryBuilder$FromStringTupleQueryBuilder$1.run(FromStringQueryBuilder.java:260)
jvm 2    |  at com.fluidops.iwb.api.ReadDataManagerImpl.run(ReadDataManagerImpl.java:3292)
jvm 2    |  at com.fluidops.iwb.api.query.FromStringQueryBuilder$FromStringTupleQueryBuilder.doPrepareQuery(FromStringQueryBuilder.java:260)
jvm 2    |  at com.fluidops.iwb.api.query.FromStringQueryBuilder$FromStringTupleQueryBuilder.doPrepareQuery(FromStringQueryBuilder.java:247)
jvm 2    |  at com.fluidops.iwb.api.query.FromStringQueryBuilder.doBuild(FromStringQueryBuilder.java:174)
jvm 2    |  at com.fluidops.iwb.api.query.QueryBuilder.build(QueryBuilder.java:307)
jvm 2    |  at org.certh.opencube.SPARQL.QueryExecutor.executeSelect(QueryExecutor.java:33)
jvm 2    |  at org.certh.opencube.SPARQL.CubeSPARQL.getCubeSliceGraph(CubeSPARQL.java:452)
jvm 2    |  at org.certh.opencube.cubebrowser.DataCubeBrowser.populateCentralContainer(DataCubeBrowser.java:243)
jvm 2    |  at org.certh.opencube.cubebrowser.DataCubeBrowser.getComponent(DataCubeBrowser.java:231)
jvm 2    |  at com.fluidops.iwb.widget.AbstractWidget$1.getComponentAsynch(AbstractWidget.java:255)
jvm 2    |  at com.fluidops.ajax.components.FAsynchContainer.handleClientSideEvent(FAsynchContainer.java:106)
jvm 2    |  at com.fluidops.ajax.AjaxServlet.doGet(AjaxServlet.java:291)
jvm 2    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
jvm 2    |  at com.fluidops.ajax.AjaxServlet.service(AjaxServlet.java:150)
jvm 2    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1367)
jvm 2    |  at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
jvm 2    |  at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:226)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1338)
jvm 2    |  at com.fluidops.servlet.CachingFilter.doFilter(CachingFilter.java:98)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1338)
jvm 2    |  at com.fluidops.iwb.user.DynamicRoleFilter.doFilter(DynamicRoleFilter.java:53)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1338)
jvm 2    |  at com.fluidops.servlet.XSSSafeHttpRequestFilter.doFilter(XSSSafeHttpRequestFilter.java:83)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1338)
jvm 2    |  at com.fluidops.servlet.LoginFilterBase.doFilter(LoginFilterBase.java:181)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1338)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:484)
jvm 2    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
jvm 2    |  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
jvm 2    |  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
jvm 2    |  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
jvm 2    |  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
jvm 2    |  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
jvm 2    |  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
jvm 2    |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
jvm 2    |  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
jvm 2    |  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
jvm 2    |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
jvm 2    |  at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:312)
jvm 2    |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
jvm 2    |  at org.eclipse.jetty.server.Server.handle(Server.java:350)
jvm 2    |  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
jvm 2    |  at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
jvm 2    |  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
jvm 2    |  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
jvm 2    |  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
jvm 2    |  at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
jvm 2    |  at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
jvm 2    |  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
jvm 2    |  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
jvm 2    |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
jvm 2    |  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
jvm 2    |  at java.lang.Thread.run(Thread.java:745)
jvm 2    | Caused by: org.openrdf.query.parser.sparql.ast.ParseException: Encountered " "/" "/ "" at line 30, column 265.
jvm 2    | Was expecting one of:
jvm 2    |     "(" ...
jvm 2    |     "!" ...
jvm 2    |     "^" ...
jvm 2    |     "a" ...
jvm 2    |     <Q_IRI_REF> ...
jvm 2    |     <PNAME_NS> ...
jvm 2    |     <PNAME_LN> ...
jvm 2    |     <VAR1> ...
jvm 2    |     <VAR2> ...
jvm 2    |  
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.generateParseException(SyntaxTreeBuilder.java:8816)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.jj_consume_token(SyntaxTreeBuilder.java:8686)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.PropertyListPath(SyntaxTreeBuilder.java:2769)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.TriplesSameSubjectPath(SyntaxTreeBuilder.java:2699)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.TriplesBlock(SyntaxTreeBuilder.java:2093)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.BasicGraphPattern(SyntaxTreeBuilder.java:1940)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:1878)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1821)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2232)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2142)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:1891)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1821)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GraphGraphPattern(SyntaxTreeBuilder.java:2209)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2145)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:1891)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1821)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.WhereClause(SyntaxTreeBuilder.java:866)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.SelectQuery(SyntaxTreeBuilder.java:313)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.Query(SyntaxTreeBuilder.java:276)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.QueryContainer(SyntaxTreeBuilder.java:164)
jvm 2    |  at org.openrdf.query.parser.sparql.ast.SyntaxTreeBuilder.parseQuery(SyntaxTreeBuilder.java:31)
jvm 2    |  at org.openrdf.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:153)
jvm 2    |  ... 64 more

**Comment by zeginis** [comment]
Which is the widget configuration you used?

**Comment by ghost** [comment]
My bad; error in id; apologies
